blog/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path
from webapp.views import IndexView, ArticleView, ArticleCreateView, \
    ArticleUpdateView, ArticleDeleteView, CommentCreateView, CommentForArticleCreateView, \
    CommentListView, CommentUpdateView, CommentDeleteView, ArticleSearchView, \
    SearchResultsView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('article/<int:pk>/', ArticleView.as_view(), name='article_view'),
    path('article/add/', ArticleCreateView.as_view(), name='article_add'),
    path('article/<int:pk>/edit/', ArticleUpdateView.as_view(), name='article_update'),
    path('article/<int:pk>/delete/', ArticleDeleteView.as_view(), name='article_delete'),
    path('article/search/', ArticleSearchView.as_view(), name='article_search'),
    path('article/search/results/', SearchResultsView.as_view(), name='search_results'),
    path('comments/', CommentListView.as_view(), name='comment_list'),
    path('comment/add/', CommentCreateView.as_view(), name='comment_add'),
    path('comment/<int:pk>/edit/', CommentUpdateView.as_view(), name='comment_update'),
    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment_delete'),
    path('article/<int:pk>/add-comment/', CommentForArticleCreateView.as_view(), name='article_comment_create'),
]

app_name = 'webapp'

webapp/models.py
from django.db import models


STATUS_ACTIVE = 'active'
STATUS_ARCHIVED = 'archived'
ARTICLE_STATUSES = (
    (STATUS_ACTIVE, 'Active'),
    (STATUS_ARCHIVED, 'Archived')
)


class Article(models.Model):
    title = models.CharField(max_length=200, null=False, blank=False, verbose_name='Заголовок')
    text = models.TextField(max_length=3000, null=False, blank=False, verbose_name='Текст')
    author = models.CharField(max_length=40, null=False, blank=False, default='Unknown', verbose_name='Автор')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время изменения')
    category = models.ForeignKey('Category', on_delete=models.PROTECT, null=True, blank=True, verbose_name='Категория',
                                 related_name='articles')
    tags = models.ManyToManyField('webapp.Tag', related_name='articles', blank=True, verbose_name='Теги')
    status = models.CharField(max_length=20, default=STATUS_ACTIVE, choices=ARTICLE_STATUSES, verbose_name='Статус')

    def __str__(self):
        return self.title

    @property
    def is_active(self):
        return self.status == STATUS_ACTIVE

    @property
    def is_archived(self):
        return self.status == STATUS_ARCHIVED


class Comment(models.Model):
    article = models.ForeignKey('webapp.Article', related_name='comments',
                                on_delete=models.CASCADE, verbose_name='Статья')
    text = models.TextField(max_length=400, verbose_name='Комментарий')
    author = models.CharField(max_length=40, null=True, blank=True, default='Аноним', verbose_name='Автор')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время изменения')

    def __str__(self):
        return self.text[:20]


class Category(models.Model):
    name = models.CharField(max_length=20, verbose_name='Название')

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=31, verbose_name='Тег')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')

    def __str__(self):
        return self.name

webapp/views/article_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.utils.http import urlencode
from django.views.generic import ListView, DetailView, CreateView,\
    UpdateView, DeleteView, FormView
from django.core.paginator import Paginator

from webapp.forms import ArticleForm, ArticleCommentForm, FullSearchForm
from webapp.models import Article, STATUS_ARCHIVED, STATUS_ACTIVE
from .base_views import SimpleSearchView


class IndexView(SimpleSearchView):
    template_name = 'article/index.html'
    context_object_name = 'articles'
    model = Article
    ordering = ['-created_at']
    paginate_by = 5
    paginate_orphans = 1

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['archived_articles'] = self.get_archived_articles()
        return context

    def get_queryset(self):
        return super().get_queryset().filter(status=STATUS_ACTIVE)

    def get_query(self):
        return Q(title__icontains=self.search_query) \
                | Q(author__icontains=self.search_query)

    def get_archived_articles(self):
        return super().get_queryset().filter(status=STATUS_ARCHIVED)


class ArticleSearchView(FormView):
    template_name = 'article/search.html'
    form_class = FullSearchForm

    def form_valid(self, form):
        query = urlencode(form.cleaned_data)
        url = reverse('webapp:search_results') + '?' + query
        return redirect(url)


class SearchResultsView(ListView):
    model = Article
    template_name = 'article/search.html'
    context_object_name = 'articles'
    paginate_by = 5
    paginate_orphans = 2

    def get_queryset(self):
        queryset = super().get_queryset()
        form = FullSearchForm(data=self.request.GET)
        if form.is_valid():
            query = self.get_text_query(form) & self.get_author_query(form)
            queryset = queryset.filter(query).distinct()
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        form = FullSearchForm(data=self.request.GET)
        query = self.get_query_string()
        return super().get_context_data(
            form=form, query=query, object_list=object_list, **kwargs
        )

    def get_query_string(self):
        data = {}
        for key in self.request.GET:
            if key != 'page':
                data[key] = self.request.GET.get(key)
        return urlencode(data)

    def get_author_query(self, form):
        query = Q()
        author = form.cleaned_data.get('author')
        if author:
            article_author = form.cleaned_data.get('article_author')
            if article_author:
                query = query | Q(author__iexact=author)
            comment_author = form.cleaned_data.get('comment_author')
            if comment_author:
                query = query | Q(comments__author__iexact=author)
        return query

    def get_text_query(self, form):
        query = Q()
        text = form.cleaned_data.get('text')
        if text:
            in_title = form.cleaned_data.get('in_title')
            if in_title:
                query = query | Q(title__icontains=text)
            in_text = form.cleaned_data.get('in_text')
            if in_text:
                query = query | Q(text__icontains=text)
            in_tags = form.cleaned_data.get('in_tags')
            if in_tags:
                query = query | Q(tags__name__iexact=text)
            in_comment_text = form.cleaned_data.get('in_comment_text')
            if in_comment_text:
                query = query | Q(comments__text__icontains=text)
        return query


class ArticleView(DetailView):
    template_name = 'article/article.html'
    model = Article

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        article = self.object
        context['form'] = ArticleCommentForm()
        comments = article.comments.order_by('-created_at')
        self.paginate_comments_to_context(comments, context)
        return context

    def paginate_comments_to_context(self, comments, context):
        paginator = Paginator(comments, 3, 0)
        page_number = self.request.GET.get('page', 1)
        page = paginator.get_page(page_number)
        context['paginator'] = paginator
        context['page_obj'] = page
        context['comments'] = page.object_list
        context['is_paginated'] = page.has_other_pages()


class ArticleCreateView(CreateView):
    form_class = ArticleForm
    model = Article
    template_name = 'article/create.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:article_view', kwargs={'pk': self.object.pk})


class ArticleUpdateView(LoginRequiredMixin, UpdateView):
    model = Article
    template_name = 'article/update.html'
    form_class = ArticleForm
    context_object_name = 'article'

    def get_success_url(self):
        return reverse('webapp:article_view', kwargs={'pk': self.object.pk})


class ArticleDeleteView(LoginRequiredMixin, DeleteView):
    model = Article
    template_name = 'article/delete.html'
    context_object_name = 'article'
    success_url = reverse_lazy('webapp:index')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.status = STATUS_ARCHIVED
        self.object.save()
        return redirect(self.get_success_url())

webapp/views/base_views.py
from django.db.models import Q
from django.shortcuts import get_object_or_404, render, redirect
from django.utils.http import urlencode
from django.views import View
from django.views.generic import TemplateView, ListView as DjangoListView

from webapp.forms import SimpleSearchForm


class ListView(TemplateView):
    context_key = 'objects'
    model = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.context_key] = self.get_objects()
        return context

    def get_objects(self):
        return self.model.objects.all()


class DetailView(TemplateView):
    context_key = 'object'
    model = None
    key_kwarg = 'pk'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.context_key] = self.get_object()
        return context

    def get_object(self):
        pk = self.kwargs.get(self.key_kwarg)
        return get_object_or_404(self.model, pk=pk)


class CreateView(View):
    form_class = None
    template_name = None
    model = None
    redirect_url = None

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, context={'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_redirect_url(self):
        return self.redirect_url

    def form_valid(self, form):
        self.object = self.model.objects.create(**form.cleaned_data)
        return redirect(self.get_redirect_url())

    def form_invalid(self, form):
        return render(self.request, self.template_name, context={'form': form})


class UpdateView(View):
    form_class = None
    template_name = None
    redirect_url = ''
    model = None
    key_kwarg = 'pk'
    context_key = 'object'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.form_class(initial=self.get_form_initial())
        context = self.make_context(form)
        return render(request, self.template_name, context=context)

    def get_form_initial(self):
        model_fields = [field.name for field in self.model._meta.fields]
        initial = {}
        for field in model_fields:
            initial[field] = getattr(self.object, field)
        print(initial)
        return initial

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        self.object = self.get_object()
        for field, value in form.cleaned_data.items():
            setattr(self.object, field, value)
        self.object.save()
        return redirect(self.get_redirect_url())

    def form_invalid(self, form):
        context = self.make_context(form)
        return render(self.request, self.template_name, context=context)

    def get_object(self):
        pk = self.kwargs.get(self.key_kwarg)
        return get_object_or_404(self.model, pk=pk)

    def make_context(self, form):
        return {
            'form': form,
            self.context_key: self.object
        }

    def get_redirect_url(self):
        return self.redirect_url


class DeleteView(View):
    template_name = None
    confirm_deletion = True
    model = None
    key_kwarg = 'pk'
    context_key = 'object'
    redirect_url = ''

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.confirm_deletion:
            return render(request, self.template_name, self.get_context_data())
        else:
            self.perform_delete()
            return redirect(self.get_redirect_url())

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.perform_delete()
        return redirect(self.get_redirect_url())

    def perform_delete(self):
        self.object.delete()

    def get_context_data(self, **kwargs):
        return {self.context_key: self.object}

    def get_object(self):
        pk = self.kwargs.get(self.key_kwarg)
        return get_object_or_404(self.model, pk=pk)

    def get_redirect_url(self):
        return self.redirect_url


class SimpleSearchView(DjangoListView):
    search_form_class = SimpleSearchForm
    form_search_field = 'search'

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_query = self.get_search_query()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        if self.search_query:
            data = {self.form_search_field: self.search_query}
            context['query'] = urlencode(data)
        context['form'] = self.form
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_query:
            query = self.get_query()
            queryset = queryset.filter(query).distinct()
        return queryset

    def get_query(self):
        return Q()

    def get_search_form(self):
        return self.search_form_class(self.request.GET)

    def get_search_query(self):
        if self.form.is_valid():
            return self.form.cleaned_data[self.form_search_field]
        return None

webapp/templates/article/article.html
{% extends 'base.html' %}

{% block title %}{{ article.title }}{% endblock %}

{% block menu %}
    <li><a href="{% url 'webapp:article_update' article.pk %}">Edit</a></li>
    <li><a href="{% url 'webapp:article_delete' article.pk %}">Delete</a></li>
    {% if article.is_active %}
        <li><a href="#add_comment">Add Comment</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <h1>{{ article.title }}</h1>
    <p>Created by {{ article.author }} ({{ article.category|default_if_none:'Без категории' }})
        at {{ article.created_at|date:'d.m.Y H:i:s' }}</p>
    <div class="pre">{{ article.text }}</div>
    <hr/>
    <h3>Comments:</h3>
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
    <div class="comment-list">
        {% for comment in comments %}
            <div class="comment">
                <p>{{ comment.author }} commented at {{ comment.created_at|date:'d.m.Y H:i:s' }}</p>
                <div class="pre">{{ comment.text }}</div>
                {% if article.is_active %}
                    <p class="comment-links">
                        <a href="{% url 'webapp:comment_update' comment.pk %}">Edit</a>
                        <a href="{% url 'webapp:comment_delete' comment.pk %}">Delete</a>
                    </p>
                {% endif %}
            </div>
        {% empty %}
            <p>No comments yet.</p>
        {% endfor %}
    </div>
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
    {% if article.is_active %}
        <form action="{% url 'webapp:article_comment_create' article.pk %}" method="POST" id="add_comment">
            {% include 'partial/form.html' with button_text='Add' %}
        </form>
    {% endif %}
{% endblock %}

webapp/templates/article/create.html
{% extends 'base.html' %}

{% block title %}Create Article{% endblock %}

{% block content %}
    <h1>Create Article</h1>
    <form method="POST" action="{% url 'webapp:article_add' %}">
        {% include 'partial/form.html' with button_text="Create" %}
    </form>
{% endblock %}

webapp/templates/article/delete.html
{% extends 'base.html' %}

{% block title %}Delete Article{% endblock %}

{% block menu %}
    <li><a href="{% url 'webapp:article_view' article.pk %}">View</a></li>
{% endblock %}

{% block content %}
    <h1>Are you sure want to delete article "{{ article }}"?</h1>
    <form method="POST" action="{% url 'webapp:article_delete' article.pk %}" class="text-center">
        {% csrf_token %}
        <p><input type="submit" value="Confirm"></p>
        <p><a href="{% url 'webapp:article_view' article.pk %}">Cancel</a></p>
    </form>
{% endblock %}

webapp/templates/article/index.html
{% extends 'base.html' %}

{% block menu %}
    {% if request.user.is_authenticated %}
        <li><a href="{% url 'webapp:article_add' %}">Add Article</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <section>
        <h1>Articles:</h1>
        {% include 'partial/simple_search.html' %}
        {% if is_paginated %}
            {% include 'partial/pagination.html' %}
        {% endif %}
        {% include 'article/partial/article_list.html' %}
        {% if is_paginated %}
            {% include 'partial/pagination.html' %}
        {% endif %}
    </section>
    <section>
        <h1>Archive</h1>
        {% for article in archived_articles %}
            <h2>{{ article.title }}</h2>
            <p>Created by {{ article.author }} ({{ article.category|default_if_none:'Без категории' }})
                at {{ article.created_at|date:'d.m.Y H:i:s' }}</p>
            <p>
                <a href="{% url 'webapp:article_view' article.pk %}">More...</a>
                <a href="{% url 'webapp:article_update' article.pk %}">Edit</a>
                <a href="{% url "webapp:article_delete" article.pk %}">Delete</a>
            </p>
            <hr/>
        {% endfor %}
    </section>
{% endblock %}

webapp/templates/article/search.html
{% extends 'base.html' %}

{% block content %}
    <form method="post" action="{% url "webapp:article_search" %}">
        {% csrf_token %}
        {% for error in form.non_field_errors %}
            <p class="form-error">{{ error }}</p>
        {% endfor %}
        {% for field in form %}
            <p><label for="{{ field.id_for_label }}">{{ field.label }}</label>: {{ field }}</p>
            {% for error in field.errors %}
                <p class="form-error">{{ error }}</p>
            {% endfor %}
        {% endfor %}
        <p><input type="submit" value="Search"></p>
    </form>
    <h1>Results</h1>
    {% if articles %}
        {% if is_paginated %}
            {% include 'partial/pagination.html' %}
        {% endif %}
        {% include 'article/partial/article_list.html' %}
    {% else %}
        <p class="text-center">No results available. Try again later or with other search params.</p>
    {% endif %}
{% endblock %}

webapp/templates/article/update.html
{% extends 'base.html' %}

{% block title %}Update Article{% endblock %}

{% block menu %}
    <li><a href="{% url 'webapp:article_view' article.pk %}">View</a></li>
{% endblock %}

{% block content %}
    <h1>Update Article</h1>
    <form method="POST" action="{% url 'webapp:article_update' article.pk %}">
        {% include 'partial/form.html' with button_text="Update" %}
    </form>
{% endblock %}