accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import register_view, user_activate_view, \
    UserDetailView, UserChangeView, UserChangePasswordView, \
    password_reset_email_view, PasswordResetFormView


urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', register_view, name='register'),
    path('activate/<token>/', user_activate_view, name='user_activate'),
    path('profile/<pk>/', UserDetailView.as_view(), name='user_detail'),
    path('profile/<pk>/edit/', UserChangeView.as_view(), name='user_update'),
    path('profile/<pk>/change-password/', UserChangePasswordView.as_view(), name='user_change_password'),
    path('reset-password/', password_reset_email_view, name='password_reset_email'),
    path('reset-password/<token>/', PasswordResetFormView.as_view(), name='password_reset_form')
]


app_name = 'accounts'

blog/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path
from webapp.views import IndexView, ArticleView, ArticleCreateView, \
    ArticleUpdateView, ArticleDeleteView, CommentCreateView, CommentForArticleCreateView, \
    CommentListView, CommentUpdateView, CommentDeleteView, ArticleSearchView, \
    SearchResultsView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('article/<int:pk>/', ArticleView.as_view(), name='article_view'),
    path('article/add/', ArticleCreateView.as_view(), name='article_add'),
    path('article/<int:pk>/edit/', ArticleUpdateView.as_view(), name='article_update'),
    path('article/<int:pk>/delete/', ArticleDeleteView.as_view(), name='article_delete'),
    path('article/search/', ArticleSearchView.as_view(), name='article_search'),
    path('article/search/results/', SearchResultsView.as_view(), name='search_results'),
    path('comments/', CommentListView.as_view(), name='comment_list'),
    path('comment/add/', CommentCreateView.as_view(), name='comment_add'),
    path('comment/<int:pk>/edit/', CommentUpdateView.as_view(), name='comment_update'),
    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment_delete'),
    path('article/<int:pk>/add-comment/', CommentForArticleCreateView.as_view(), name='article_comment_create'),
]

app_name = 'webapp'

accounts/models.py
from django.db import models
from uuid import uuid4
from django.contrib.auth.models import User


class Token(models.Model):
    token = models.UUIDField(verbose_name='Token', default=uuid4)
    user = models.ForeignKey('auth.User', related_name='registration_tokens',
                             verbose_name='User', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.token)


class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE,
                                verbose_name='Пользователь')
    birth_date = models.DateField(null=True, blank=True, verbose_name='Дата рождения')
    avatar = models.ImageField(null=True, blank=True,
                               upload_to='user_pics', verbose_name='Аватар')

    def __str__(self):
        return self.user.get_full_name() + "'s Profile"

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from accounts.models import Profile


class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True, label='Email')

    class Meta(UserCreationForm.Meta):
        fields = ('username', 'email')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            User.objects.get(email=email)
            raise ValidationError('Email already registered.', code='email_registered')
        except User.DoesNotExist:
            return email


class UserChangeForm(forms.ModelForm):
    avatar = forms.ImageField(label='Аватар', required=False)
    birth_date = forms.DateField(label='День рождения', input_formats=['%Y-%m-%d', '%d.%m.%Y'], required=False)

    def get_initial_for_field(self, field, field_name):
        if field_name in self.Meta.profile_fields:
            return getattr(self.instance.profile, field_name)
        return super().get_initial_for_field(field, field_name)

    def save(self, commit=True):
        user = super().save(commit=commit)
        # это присваивание необходимо, чтобы при commit=False
        # профиль пользователя все равно обновлялся.
        # если commit равен False, то после сохранения формы нужно
        # вручную вызвать:
        # user.save()
        # user.profile.save()
        # чтобы сохранить обе модели.
        user.profile = self.save_profile(commit)
        return user

    def save_profile(self, commit=True):
        profile, _ = Profile.objects.get_or_create(user=self.instance)
        for field in self.Meta.profile_fields:
            setattr(profile, field, self.cleaned_data.get(field))
        if not profile.avatar:
            profile.avatar = None
        if commit:
            profile.save()
        return profile

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']
        profile_fields = ['avatar', 'birth_date']


class UserChangePasswordForm(forms.ModelForm):
    password = forms.CharField(max_length=100, required=True, label='New Password',
                               widget=forms.PasswordInput)
    password_confirm = forms.CharField(max_length=100, required=True, label='New Password confirm',
                                       widget=forms.PasswordInput)
    old_password = forms.CharField(max_length=100, required=True, label='Old Password',
                                   widget=forms.PasswordInput)

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        user = self.instance
        if not user.check_password(old_password):
            raise ValidationError('Invalid password.', code='invalid_password')
        return old_password

    def clean(self):
        super().clean()
        password_1 = self.cleaned_data.get('password')
        password_2 = self.cleaned_data.get('password_confirm')
        if password_1 != password_2:
            raise ValidationError('Passwords do not match.', code='passwords_do_not_match')
        return self.cleaned_data

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data.get('password'))
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['password', 'password_confirm', 'old_password']


class UserPasswordResetForm(forms.ModelForm):
    password = forms.CharField(max_length=100, required=True, label='New Password',
                               widget=forms.PasswordInput)
    password_confirm = forms.CharField(max_length=100, required=True, label='New Password confirm',
                                       widget=forms.PasswordInput)

    def clean(self):
        super().clean()
        password_1 = self.cleaned_data.get('password')
        password_2 = self.cleaned_data.get('password_confirm')
        if password_1 != password_2:
            raise ValidationError('Passwords do not match.', code='passwords_do_not_match')
        return self.cleaned_data

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data.get('password'))
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = []

accounts/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.urls import reverse
from django.views.generic import UpdateView, DetailView

from accounts.models import Token, Profile
from blog.settings import HOST_NAME

from accounts.forms import SignUpForm, UserChangeForm, UserChangePasswordForm, UserPasswordResetForm


def send_token(user, subject, message, redirect_url):
    token = Token.objects.create(user=user)
    url = HOST_NAME + reverse(redirect_url, kwargs={'token': token})
    print(url)
    try:
        user.email_user(subject, message.format(url=url))
    except ConnectionRefusedError:
        print('Could not send email. Server error.')


def register_view(request):
    if request.method == 'GET':
        form = SignUpForm()
        return render(request, 'register.html', context={'form': form})
    elif request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            Profile.objects.create(user=user)
            send_token(user,
                       'Вы зарегистрировались на сайте localhost:8000.',
                       'Для активации перейдите по ссылке: {url}',
                       redirect_url='accounts:user_activate')
            return redirect('webapp:index')
        else:
            return render(request, 'register.html', context={'form': form})


def user_activate_view(request, token):
    token = get_object_or_404(Token, token=token)
    user = token.user
    user.is_active = True
    user.save()
    token.delete()
    login(request, user)
    return redirect('webapp:index')


class UserDetailView(DetailView):
    model = User
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'


class UserChangeView(UserPassesTestMixin, UpdateView):
    model = User
    template_name = 'user_update.html'
    context_object_name = 'user_obj'
    form_class = UserChangeForm

    def test_func(self):
        return self.get_object() == self.request.user

    def get_success_url(self):
        return reverse('accounts:user_detail', kwargs={'pk': self.object.pk})


class UserChangePasswordView(UserPassesTestMixin, UpdateView):
    model = User
    template_name = 'user_change_password.html'
    form_class = UserChangePasswordForm
    context_object_name = 'user_obj'

    def test_func(self):
        return self.get_object() == self.request.user

    def get_success_url(self):
        return reverse('accounts:login')


def password_reset_email_view(request):
    if request.method == 'GET':
        return render(request, 'password_reset_email.html')
    elif request.method == 'POST':
        email = request.POST.get('email')
        users = User.objects.filter(email=email)
        if len(users) > 0:
            user = users[0]
            send_token(user,
                       'Вы запросили восстановление пароля на сайте localhost:8000.',
                       'Для ввода нового пароля перейдите по ссылке: {url}',
                       redirect_url='accounts:password_reset_form')
        return render(request, 'password_reset_confirm.html')


class PasswordResetFormView(UpdateView):
    model = User
    template_name = 'password_reset_form.html'
    form_class = UserPasswordResetForm
    context_object_name = 'user_obj'

    def get_object(self, queryset=None):
        token = self.get_token()
        return token.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['token'] = self.kwargs.get('token')
        return context

    def form_valid(self, form):
        token = self.get_token()
        token.delete()
        return super().form_valid(form)

    def get_token(self):
        token_value = self.kwargs.get('token')
        return get_object_or_404(Token, token=token_value)

    def get_success_url(self):
        return reverse('accounts:login')

accounts/templates/password_reset_confirm.html
{% extends 'base.html' %}
{% block content %}
    <div class="text-center">
        <h1>Password reset</h1>
        <p>Email with instructions was sent to specified address.</p>
        <p><a href="{% url 'webapp:index' %}">Back Home</a></p>
    </div>
{% endblock %}

accounts/templates/password_reset_email.html
{% extends 'base.html' %}
{% block content %}
    <h1>Password reset</h1>
    <form action="{% url 'accounts:password_reset_email' %}" method="post" class="text-center">
        {% csrf_token %}
        <label for="email">Email: </label><input type="email" name="email" id="email">
        <input type="submit" value="Submit">
    </form>
{% endblock %}

accounts/templates/password_reset_form.html
{% extends 'base.html' %}
{% block content %}
    <h1>Password reset</h1>
    <form action="{% url 'accounts:password_reset_form' token %}" method="post" class="text-center">
        {% include 'partial/form.html' with button_text="Reset" %}
    </form>
{% endblock %}

accounts/templates/register.html
{% extends 'base.html' %}
{% block content %}
    <h1>Sign Up</h1>
    <form method="post" action="{% url 'accounts:register' %}" class="text-center">
        {% include 'partial/form.html' with button_text='Register' %}
    </form>
{% endblock %}

accounts/templates/user_change_password.html
{% extends 'base.html' %}
{% block title %}{{ user_obj.username }}{% endblock %}
{% block menu %}
    {% if user_obj == request.user %}
        <li><a href="{% url 'accounts:user_detail' user_obj.pk %}">View</a></li>
        <li><a href="{% url 'accounts:user_update' user_obj.pk %}">Edit Profile</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <h1>Change Password: {{ user_obj.username }}</h1>
    <form action="{% url 'accounts:user_change_password' user_obj.pk %}" method="post">
        {% include 'partial/form.html' with button_text="Save" %}
    </form>
{% endblock %}

accounts/templates/user_detail.html
{% extends 'base.html' %}
{% block title %}{{ user_obj.username }}{% endblock %}
{% block menu %}
    {% if user_obj == request.user %}
        <li><a href="{% url "accounts:user_update" user_obj.pk %}">Edit Profile</a></li>
        <li><a href="{% url 'accounts:user_change_password' user_obj.pk %}">Change Password</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <h1>Profile: {{ user_obj.username }}</h1>
    {% if user_obj.profile.avatar %}
        <img class="avatar" src="{{ user_obj.profile.avatar.url }}" alt="user-pic">
    {% endif %}
    <p>First Name: {{ user_obj.first_name }}</p>
    <p>Last Name: {{ user_obj.last_name }}</p>
    <p>Email: {{ user_obj.email }}</p>
    <p>Birth Date: {{ user_obj.profile.birth_date|date:"d.m.Y" }}</p>
{% endblock %}

accounts/templates/user_update.html
{% extends 'base.html' %}
{% block title %}{{ user_obj.username }}{% endblock %}
{% block menu %}
    {% if user_obj == request.user %}
        <li><a href="{% url 'accounts:user_detail' user_obj.pk %}">View</a></li>
        <li><a href="{% url 'accounts:user_change_password' user_obj.pk %}">Change Password</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <h1>Edit Profile: {{ user_obj.username }}</h1>
    <form action="{% url 'accounts:user_update' user_obj.pk %}" method="post"
        enctype="multipart/form-data">
        {% include 'partial/form.html' with button_text="Update" %}
    </form>
{% endblock %}